name: CI Pipeline (Day-10)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_NAME: devops-ci-demo

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment vairables
        run: |
          echo "App Name: $APP_NAME"
          echo "Runner OS: $RUNNER_OS"



name: Day 9 - CI Demo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-shell-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check script exists
        run: |
          test -f projects/Day-9/CI-Demo/hello.sh

      - name: Check bash shebang
        run: |
          head -n 1 projects/Day-9/CI-Demo/hello.sh | grep "#!/bin/bash"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run hello script
        run: |
          chmod +x projects/Day-9/CI-Demo/hello.sh
          ./projects/Day-9/CI-Demo/hello.sh
