name: CI Pipeline (Day-10)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  APP_NAME: devops-ci-demo

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment vairables
        run: |
          echo "App Name: $APP_NAME"
          echo "Runner OS: $RUNNER_OS"

      - name: Run Day-9 script
        run: |
          chmod +x projects/Day-9/CI-Demo/hello.sh
          ./projects/Day-9/CI-Demo/hello.sh

      - name: Run build script
        run: |
          chmod +x projects/Day-10/demo-build/build.sh
          ./projects/Day-10/demo-build/build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifacts@v4
        with:
          name: build-output
          path: projects/Day-10/build-demo/output/build.txt

